name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name:  Run Unit Tests
        run: ./gradlew test

      - name: Send Discord notification
        uses: stegzilla/discord-notify@v2
        with:
          webhook_url: ${{ secrets.DISCORD_SECRET }}
          title: NEW PUSH TO STOCK APP
          message: "${{ github.event.pull_request.title }}  \n Repository : ${{ github.repository }} \n  Creator : ${{ github.actor }} \n Obrigado Ricardo por esta oportunidade"
          include_image: true
          username: 'Yo mama'
          avatar_url: 'https://i.pinimg.com/originals/a8/91/8a/a8918a2421977089bc5c167158cff466.png'
