name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name:  Run Unit Tests
        run: ./gradlew test

      
      - name: Discord notification
        uses: cl8dep/action-discord@v0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: '104 Kilos de formusura'
          username: 'A tua mãe'
          avatar: 'https://i.pinimg.com/originals/a8/91/8a/a8918a2421977089bc5c167158cff466.png'
